---
title "Exploring Flowcharts using DiagrammeR - 2023_flowcharts_ver2e.Rmd"
author: "Rebecca Handcock"
date: "2023-12-14"
output: html_document
---

```{r message=TRUE, paged.print=TRUE}
#------------------------------------------------|
# Set BigQuery files
# This would ideally be done programatically, but for now is hard-coded
#------------------------------------------------|

# Academic Observatory - this is the version of the Academic Observatory
COKI_AcademicObservatory_table <- "academic-observatory.observatory.doi20231210"
COKI_AcademicObservatory_var1 <- "doi"

# ----------------------------------------------------------------------

# Contributed DATA: pubs - List of pubs/DOI of interest in the project
#ORG_dois_YYYMM22.txt
ORG_dois_raw <- "ORG_dois_YYYMM22.txt [TheNeuro_dois_2010-2022.csv]"
ORG_dois_table <- "university-of-ottawa.neuro_data_raw.raw20230217_theneuro_dois_20102022_tidy_long"
ORG_dois_var1 <- "doi"

# Contributed DATA: trials - List of actual clinical trials for the organisation
# ORG_trials_YYYMM22.txt
ORG_trials_raw <- "ORG_trials_YYYMM22.txt"

# Contributed DATA: ORCID - List of ORCIDs for researchers for the organisation
# ORG_orcid_YYYMM22.txt
ORG_orcid_raw <- "ORG_orcid_YYYMM22.txt \\n[neuro_pis_orcid.csv]"
ORG_orcid_table <- "university-of-ottawa.neuro_data_raw.neuro_pis_orcid"
ORG_orcid_var1 <- "orcid_id"

# ----------------------------------------------------------------------
# OLD Contributed DATA: Oddpub - Output from the Oddpub processing
# NEW DATA: Project Process- Oddpub - Output from the Oddpub processing
PROJECT_Oddpub_raw <- "NEURO_oddpub_screening.csv"
PROJECT_Oddpub_table <- "university-of-ottawa.neuro_data_raw.raw20230217_theneuro_oddpub_screening_tidy"
PROJECT_Oddpub_var1 <- "doi"

# NEW DATA: Project Process- Charite - Output from the Charite processing
PROJECT_trials_raw <- "combined-ctgov-studies.csv"
PROJECT_trials_table <- "university-of-ottawa.neuro_data_raw.montreal_neuro-studies_ver2_raw"
PROJECT_trials_var1 <- "nct_id"

# ----------------------------------------------------------------------
# Note, processing Step #1 only produces an intermediate table, so is not 
# included in the dashbaord output tables

# Output dashboard data - from the SQL - Step 2 - Clinical Trial data for institution
DASHBOARD_trials_table <- "university-of-ottawa.neuro_dashboard_data.dashboard_data_trials"
DASHBOARD_trials_var1 <- "nct_id"

# Output dashboard data - from the SQL - Step 3 - Pubs
DASHBOARD_pubs_table <- "university-of-ottawa.neuro_dashboard_data.dashboard_data_pubs"
DASHBOARD_pubs_var1 <- "doi"

# Output dashboard data - from the SQL - Step 4 - ORCID for researchers
DASHBOARD_orcid_table <- "university-of-ottawa.neuro_dashboard_data.dashboard_data_orcid"
DASHBOARD_orcid_var1 <- "orcid_id"

```

```{r warning=FALSE, message=FALSE, include=FALSE}
#------------------------------------------------|
# setup packages
#------------------------------------------------|

# Github: https://github.com/rich-iannone/DiagrammeR
# Functions: https://rich-iannone.github.io/DiagrammeR/reference/index.html
# Package: https://cran.r-project.org/web/packages/DiagrammeR/DiagrammeR.pdf
# Tutorial: https://epirhandbook.com/en/diagrams-and-charts.html
# Reference; https://graphviz.org/pdf/dotguide.pdf
# Turotial: https://builtin.com/data-science/diagrammer

# DiagrammeR is a package within htmlwidgets for R. It is used to generate graphs using graphviz and mermaid library.
#install.packages("DiagrammeR")
library(DiagrammeR)

# rsvg: Renders vector-based svg images into images
library(rsvg)

# Connect to Bigquery
library(bigrquery)
library(DBI)

# helpful libraries
library(stringr)
library(dplyr)
library(purrr)

```


```{r message=FALSE, warning=FALSE}
#------------------------------------------------|
# FUNCTION F_bigquery_sql_count_distinct 
#------------------------------------------------|

F_bigquery_sql_count_distinct <- function(F_table, F_variable){
  
  # Set up query generics
  # SELECT COUNT(DISTINCT published_year) AS count_dist_x FROM `university-of-ottawa.neuro_dashboard_data.dashboard_data_pubs`
  sql_prefix <- "SELECT COUNT(DISTINCT "
  sql_middle <- ") FROM `"
  sql_end <- "`"

  sql <- paste(sql_prefix, F_variable, sql_middle,  F_table, sql_end, sep = "")

  # send the SQL to bigquery
  F_count <- dbGetQuery(con, sql)
  return(F_count)
  }
```


```{r FUNCTION: F_export_grViz_graph2image, message=FALSE, warning=FALSE}
#------------------------------------------------|
# FUNCTION export grViz graph to an image file
#------------------------------------------------|

F_export_grViz_graph2image <- function(graph2plot){
  # 1. Process the graph
  tmp = DiagrammeR::grViz(graph2plot)

  # 2. Convert to SVG, then save as png
  tmp = DiagrammeRsvg::export_svg(tmp)
  tmp = charToRaw(tmp) # flatten
  filename <- paste(deparse(substitute(graph2plot)), ".png", sep = "")
  print(filename)
  rsvg::rsvg_png(tmp, filename) # saved graph as png in current working directory
  }
```


```{r Connect to BigQuery database}
#------------------------------------------------|
# Connect to BigQuery database
#------------------------------------------------|

# --- To query BigQuery data with R and BigQuery, you first need to set up a connection to a data set using this syntax:
# con <- dbConnect(
#   bigquery(),
#   project = "university-of-ottawa",
#   dataset = "neuro_dashboard_data",
#   billing = "university-of-ottawa"
# )

con <- dbConnect(
  bigquery(),
  project = "university-of-ottawa",
  dataset = "neuro_dashboard_data",
  billing = "university-of-ottawa"
)
# Now run a simple query to prompt authenticating your Google account

dbListTables(con)

```


```{r Process Bigquery files, message=TRUE, messages=TRUE, paged.print=TRUE}
#------------------------------------------------|
# Fetch information about BigQuery datasets
# These values will be displayed later in the flowchart
#------------------------------------------------|

# Contributed DATA: pubs - List of pubs/DOI of interest in the project
ORG_dois_table_short <- str_split(ORG_dois_table, "\\.")[[1]][3]
ORG_dois_count1 <- F_bigquery_sql_count_distinct(ORG_dois_table, ORG_dois_var1)
ORG_dois_count1 <- ORG_dois_count1$f0_
print(paste("Contributed pubs (Target DOIs):",ORG_dois_table, "has", ORG_dois_count1,"distinct values for", ORG_dois_var1))
DASHBOARD_pubs_table_short <- str_split(DASHBOARD_pubs_table, "\\.")[[1]][3]

# Contributed DATA: Oddpub - Output from the Oddpub processing
PROJECT_Oddpub_table_short <- str_split(PROJECT_Oddpub_table, "\\.")[[1]][3]
PROJECT_Oddpub_count1 <- F_bigquery_sql_count_distinct(PROJECT_Oddpub_table, PROJECT_Oddpub_var1)
PROJECT_Oddpub_count1 <- PROJECT_Oddpub_count1$f0_
print(paste("Contributed ODDPUB:", PROJECT_Oddpub_table, "has", PROJECT_Oddpub_count1,"distinct values for",PROJECT_Oddpub_var1))

# Contributed DATA: trials - List of actual clinical trials for the institution
PROJECT_trials_table_short <- str_split(PROJECT_trials_table, "\\.")[[1]][3]
PROJECT_trials_count1 <- F_bigquery_sql_count_distinct(PROJECT_trials_table, PROJECT_trials_var1)
PROJECT_trials_count1 <- PROJECT_trials_count1$f0_
print(paste("CLINICAL TRIALS:", PROJECT_trials_table, "has", PROJECT_trials_count1,"distinct values for",PROJECT_trials_var1))
DASHBOARD_trials_table_short <- str_split(DASHBOARD_trials_table, "\\.")[[1]][3]

# Contributed DATA: ORCID - List of ORCIDs for researchers for the institution
ORG_orcid_table_short <- str_split(ORG_orcid_table, "\\.")[[1]][3]
ORG_orcid_count1 <- F_bigquery_sql_count_distinct(ORG_orcid_table, ORG_orcid_var1)
ORG_orcid_count1 <- ORG_orcid_count1$f0_
print(paste("Contributed ODDPUB:", ORG_orcid_table, "has", ORG_orcid_count1,"distinct values for",ORG_orcid_var1))
DASHBOARD_orcid_table_short <- str_split(DASHBOARD_orcid_table, "\\.")[[1]][3]
DASHBOARD_orcid_count1 <- F_bigquery_sql_count_distinct(DASHBOARD_orcid_table, DASHBOARD_orcid_var1)

#----------------------------------------------------------------------

# Output dashboard data - from the SQL - Step 2 - Clinical Trial data for institution
DASHBOARD_trials_table_short <- str_split(DASHBOARD_trials_table, "\\.")[[1]][3]
DASHBOARD_trials_count1 <- F_bigquery_sql_count_distinct(DASHBOARD_trials_table, DASHBOARD_trials_var1)
DASHBOARD_trials_count1 <- DASHBOARD_trials_count1$f0_
print(paste("DASHBOARD TABLE:", DASHBOARD_trials_table, "has", DASHBOARD_trials_count1,
            "distinct values for", DASHBOARD_trials_var1))

# Output dashboard data - from the SQL - Step 3 - Pubs
DASHBOARD_pubs_table_short <- str_split(DASHBOARD_pubs_table, "\\.")[[1]][3]
DASHBOARD_pubs_count1 <- F_bigquery_sql_count_distinct(DASHBOARD_pubs_table, DASHBOARD_pubs_var1)
DASHBOARD_pubs_count1 <- DASHBOARD_pubs_count1$f0_
print(paste("DASHBOARD TABLE:", DASHBOARD_pubs_table, "has", DASHBOARD_pubs_count1,
            "distinct values for", DASHBOARD_pubs_var1))

# Output dashboard data - from the SQL - Step 4 - ORCID for researchers
DASHBOARD_orcid_table_short <- str_split(DASHBOARD_orcid_table, "\\.")[[1]][3]
DASHBOARD_orcid_count1 <- F_bigquery_sql_count_distinct(DASHBOARD_orcid_table, DASHBOARD_orcid_var1)
DASHBOARD_orcid_count1 <- DASHBOARD_orcid_count1$f0_
print(paste("DASHBOARD TABLE:", DASHBOARD_orcid_table, "has", DASHBOARD_orcid_count1,
            "distinct values for", DASHBOARD_orcid_var1))

# Academic Observatory - this is the version of the Academic Observatory
COKI_AcademicObservatory_table_short <- str_split(COKI_AcademicObservatory_table, "\\.")[[1]][3]
COKI_AcademicObservatory_count1 <- F_bigquery_sql_count_distinct(COKI_AcademicObservatory_table, COKI_AcademicObservatory_var1)
COKI_AcademicObservatory_count1 <- COKI_AcademicObservatory_count1$f0_
print(paste("ACADEMIC OBSERVATORY:",COKI_AcademicObservatory_table, "has", 
            COKI_AcademicObservatory_count1,"distinct values for",COKI_AcademicObservatory_var1))
```



```{r graph_biomedical_main, fig.show='show', warning=TRUE, messages=TRUE}
#------------------------------------------------|
# Main
#------------------------------------------------|
graph_biomedical_main <- "digraph {
  # ---------------------------------------------------------
  # --- Set default attibutes
  # ---------------------------------------------------------
  layout = dot;
  compound=TRUE;
  node [shape = rectangle, fixedsize=FALSE, height=0.01 width=0.4, 
      style='filled, rounded', fillcolor=white, penwidth=1.5
      fontname = Helvetica, fontsize=16]
  edge [color=black, arrowhead=normal, arrowsize=1.5, penwidth=2.5]

  # ---------------------------------------------------------
  # DATASETS: ACADEMIC OBSERVATORY
  # ---------------------------------------------------------
  # ------ SHAPES & LABELS - Academic Observatory
  DATA_AcademicObservatory[label = 'Academic Observatory \\n@@1 \\n@@2 DOIs',fillcolor='#ff671c']

  DATA_CrossrefMeta[label='Crossref \\nMetadata',fillcolor='#FFA376']
  DATA_CrossrefFunder[label='Crossref \\nFunder \\nRegistry',fillcolor='#FFA376']
  DATA_CrossrefEvents[label='Crossref \\nEvents',fillcolor=white]
  DATA_OpenAlex[label='Open \\nAlex',fillcolor='#FFA376']
  DATA_Unpaywall[label='Unpaywall',fillcolor='#FFA376']
  DATA_ROR[label= 'Research \\nOrganization \\nRegistry',fillcolor=white]
  DATA_OpenCit[label='Open \\nCitations',fillcolor=white]
  DATA_Pubmed[label='PubMed',fillcolor='#FFA376']
  
  # ---------------------------------------------------------
  # INPUT DATASETS: ORGANISATION - RAW
  # ---------------------------------------------------------
  # ------ SHAPES & LABELS - DATA - ORG - dois
  DATA_ORG_dois_raw[label = 'publication DOIs \\n@@3',
      fillcolor='#AC94F4']

  # ------ SHAPES & LABELS - DATA - ORG - clinical trials
  DATA_ORG_trials_raw[label = 'Researcher Clinical Trials \\n@@_NEW5',
      fillcolor='#AC94F4']

  # ------ SHAPES & LABELS - DATA - ORG - orcid
  DATA_ORG_orcid_raw[label = 'Researcher ORCIDs \\n@@6_NEW4',
      fillcolor='#AC94F4']   
   
  subgraph cluster_ORG_raw {
     label='Datasets provided by the Organisation'; 
     fontsize=20; fontname='Helvetica-Bold';
     style='filled, rounded'; fillcolor='#E2D9FB';

    DATA_ORG_dois_raw
    DATA_ORG_trials_raw
    DATA_ORG_orcid_raw
  } # END cluster_ORG
  
  # ---------------------------------------------------------
  # PROCESSED DATASETS - INTERMEDIATE
  # ---------------------------------------------------------

  # ------ SHAPES & LABELS - DATA - PROCESSED - pubs dois
  DATA_PROCESSED_dois[label = 'Target publication DOIs - imported \\n@@7 \\n@@8 unique [@@9]',
      shape=rectangle, fillcolor=white]

  # ------ SHAPES & LABELS - DATA - PROCESSED - orcids
  DATA_PROCESSED_orcid[label = 'Researcher ORCIDs - imported \\n@@16 \\n@@17 unique [@@18]',
      shape=rectangle, fillcolor=white]
      


  # ------ SHAPES & LABELS - DATA - PROCESSED - trials
  DATA_PROCESSED_trials[label = 'Charite Clinical Trials - imported \\n@@13 \\n@@14 unique [@@15]',
      shape=rectangle, fillcolor=white]

  # ---------------------------------------------------------
  # PROCESSED DATASETS - DASHBOARD
  # ---------------------------------------------------------
  # ------ SHAPES & LABELS - DASHBOARD files - pubs
  OUTPUT_Dashboard_pubs[label = 'Dashboard data - Publications \\n@@19 \\n@@20 unique non-NULL [@@21]',
      shape=rectangle, fillcolor='#9DD8A1']
      
  # ------ SHAPES & LABELS - DASHBOARD files - trials
  OUTPUT_Dashboard_trials[label = 'Dashboard data - Clinical Trials \\n@@22 \\n@@23 unique non-NULL [@@24]',
      shape=rectangle, fillcolor='#9DD8A1']

  # ------ SHAPES & LABELS - DASHBOARD files - orcid
  OUTPUT_Dashboard_orcid[label = 'Dashboard data - Researcher ORCIDs \\n@@25 \\n@@26 unique non-NULL [@@27]',
      shape=rectangle, fillcolor='#9DD8A1']

  # ---------------------------------------------------------
  # LINKS: ACADEMIC OBSERVATORY
  # ---------------------------------------------------------
  subgraph cluster_AcademicObservatory {
     label='Academic Observatory'; fontsize=20; fontname = 'Helvetica-Bold';
     style='filled, rounded'; fillcolor='#FFF0E9';

     DATA_CrossrefMeta   -> DATA_AcademicObservatory
     DATA_CrossrefFunder -> DATA_AcademicObservatory 
     DATA_CrossrefEvents -> DATA_AcademicObservatory
     DATA_OpenAlex       -> DATA_AcademicObservatory
     DATA_Unpaywall      -> DATA_AcademicObservatory
     DATA_ROR            -> DATA_AcademicObservatory
     DATA_OpenCit        -> DATA_AcademicObservatory
     DATA_Pubmed         -> DATA_AcademicObservatory
  } # END cluster_AcademicObservatory

  # ---------------------------------------------------------
  # PROCESS #0_Charite - Charite clinical trial processing
  # ---------------------------------------------------------
  DATA_ORG_trials_raw -> DATA_PROCESSED_trials
    [minlen=2, ltail = cluster_ORG_raw, lhead = cluster_0_Charite]
      
  subgraph cluster_0_Charite {
    label='Charite Processing - by the project'; 
    fontsize=20; fontname='Helvetica-Bold';
    style='filled, rounded'; fillcolor='#E9FAFA';
      
    # -- Nodes
    Process_0_Charite[label = 'Charite processing', 
        shape=rectangle, style='filled, dashed', fillcolor=white]
    
    DATA_PROJECT_charite_trials_output[label = 'Output from Charite clinical trial processing \\n@@5',
      fillcolor='#2CCCD3']
      
    DATA_PROCESSED_trials -> Process_0_Charite

    Process_0_Charite -> DATA_PROJECT_charite_trials_output
    } # END cluster_0_Charite
    
  # ---------------------------------------------------------
  # PROCESS #0_Oddpub - Oddpub processing
  # ---------------------------------------------------------
  DATA_ORG_dois_raw -> DATA_PROCESSED_dois
    [minlen=2, ltail = cluster_ORG_raw, lhead = cluster_0_Oddpub]
       
  subgraph cluster_0_Oddpub{
      label='Oddpub Processing - by the project'; 
      fontsize=20; fontname='Helvetica-Bold';
      style='filled, rounded'; fillcolor='#E9FAFA';

    # -- Nodes
    Process_0_Oddpub[label = 'Oddpub processing', fontsize=18,
        shape=rectangle, style='filled, dashed', fillcolor=white]
        
    DATA_PROJECT_Oddpub_output[label = 'Output from Oddpub processing - Data and Software \\n@@4',
      fillcolor='#2CCCD3']
      
    
    # -- Links
    DATA_PROCESSED_dois -> Process_0_Oddpub [minlen=1]

    Process_0_Oddpub -> DATA_PROJECT_Oddpub_output
    
     } # END cluster_P0_Oddpub
  
  # ---------------------------------------------------------
  # PROCESS #1 - From the AO, create meta list of clinical trial numbers
  # associated with DOIs
  # ---------------------------------------------------------
  
  DATA_AcademicObservatory ->  Process_1
    [minlen=2, ltail = cluster_AcademicObservatory, lhead = cluster_1]

  subgraph cluster_1 {
    label='SQL process #1 - by COKI'; 
      fontsize=20; fontname='Helvetica-Bold';
      style='filled, rounded'; fillcolor='#D7EFD9';
 
    # -- Nodes
    Process_1[label = 'Create meta-list of clinical trial numbers associated with 
    DOIs using Crossref & Pubmed fields and abstract search', 
      shape=rectangle, style='filled, dashed', fillcolor=white]
  
    # -- Links

    Process_1 -> Intermediate_Table_1 Intermediate_Table_1
      [label = 'Intermediate Table
      All Clinical Trial Numbers found for DOIs in Crossref & Pubmed',
      fillcolor='#9DD8A1']

    } # END cluster_1
  
  # ---------------------------------------------------------
  # PROCESS #2 - SQL to combine the contributed clinical trial data
  # with the meta-list of clinical trial numbers
  # ---------------------------------------------------------

  Intermediate_Table_1 -> Process_2
    [minlen=2, ltail = cluster_1, lhead = cluster_2]
  
  subgraph cluster_2 {
    label='SQL process #2 - by COKI'; 
      fontsize=20; fontname='Helvetica-Bold';
      style='filled, rounded'; fillcolor='#D7EFD9';
      
    # -- Nodes
    Process_2[label = 'Match the contributed clinical trial data to 
      the meta-list of clinical trial numbers from 
      Pubmed and Crossref, and to the contributed DOIs', 
      shape=rectangle, style='filled, dashed', fillcolor=white]
  
    # -- Links
    DATA_PROJECT_charite_trials_output -> Process_2
      [minlen=2, ltail = cluster_0_Charite, lhead = cluster_2]

    Process_2 -> OUTPUT_Dashboard_trials
    
    } # END cluster_2

  # ---------------------------------------------------------
  # PROCESS #3 - SQL to process the ORCID data for the dashbaord
  # ---------------------------------------------------------
  DATA_ORG_orcid_raw -> DATA_PROCESSED_orcid
    [minlen=2, ltail = cluster_ORG_raw, lhead = cluster_3]

  subgraph cluster_3 {
    label='SQL process #3 - by COKI'; 
      fontsize=20; fontname='Helvetica-Bold';
      style='filled, rounded'; fillcolor='#D7EFD9';
   
    # -- Nodes
    Process_3[label = 'Process the ORCID data', 
      shape=rectangle, style='filled, dashed', fillcolor=white]

    # -- Links
    DATA_PROCESSED_orcid -> Process_3
    Process_3 -> OUTPUT_Dashboard_orcid
    
    } # END cluster_3

  # ---------------------------------------------------------
  # PROCESS #4 - SQL to process the Publication and Oddpub data for the dashboard
  # ---------------------------------------------------------
  DATA_PROJECT_Oddpub_output -> process_4
      [minlen=2, ltail = cluster_0_Oddpub, lhead = cluster_4]
      
  subgraph cluster_4 {
    label='SQL process #4 - by COKI'; 
    fontsize=20; fontname='Helvetica-Bold';
    style='filled, rounded'; fillcolor='#D7EFD9';

    # -- Nodes
    DATA_PROCESSED_oddpub[label = 'Oddpub output - imported \\n@@10 \\n@@11 unique [@@12]',
      shape=rectangle, fillcolor=white]
      
    process_4[label = 'Process the Publication and Oddpub data', 
      fontsize=18, shape=rectangle, style='filled, dashed', fillcolor=white]

    # -- Links
    DATA_PROCESSED_oddpub -> process_4
    Intermediate_Table_1 -> process_4
      [minlen=2, ltail = cluster_1, lhead = cluster_4]

    process_4 -> OUTPUT_Dashboard_pubs
      
  } # END cluster_4

  # ---------------------------------------------------------
  # Main dashboard
  # ---------------------------------------------------------

  # ------ SHAPES & LABELS - Dashboard
  OUTPUT_Dashboard[label = 'Dashboard', fontname='Helvetica-Bold', fontsize=20,
      shape=filled, fillcolor='#3BB143']
     
  OUTPUT_Dashboard_trials -> OUTPUT_Dashboard
      [minlen=2, ltail = cluster_2]
      
  OUTPUT_Dashboard_orcid -> OUTPUT_Dashboard
      [minlen=2, ltail = cluster_3]
    
  OUTPUT_Dashboard_pubs -> OUTPUT_Dashboard
      [minlen=2, ltail = cluster_4]
      
  #rank=same {Process_2, Process_3, process_4}
  #rank=same {OUTPUT_Dashboard_pubs, OUTPUT_Dashboard_trials, OUTPUT_Dashboard_orcid}
  
  # ------ Add footnotes 
  }
  [1]:COKI_AcademicObservatory_table_short
  [2]:COKI_AcademicObservatory_count1
  [3]:ORG_dois_raw
  [4]:PROJECT_Oddpub_raw
  [5]:PROJECT_trials_raw
  [6]:ORG_orcid_raw
  [7]:ORG_dois_table_short
  [8]:ORG_dois_count1
  [9]:ORG_dois_var1
  [10]:PROJECT_Oddpub_table_short
  [11]:PROJECT_Oddpub_count1
  [12]:PROJECT_Oddpub_var1
  [13]:PROJECT_trials_table_short
  [14]:PROJECT_trials_count1
  [15]:PROJECT_trials_var1
  [16]:ORG_orcid_table_short
  [17]:ORG_orcid_count1
  [18]:ORG_orcid_var1
  [19]:DASHBOARD_pubs_table_short
  [20]:DASHBOARD_pubs_count1  
  [21]:DASHBOARD_pubs_var1
  [22]:DASHBOARD_trials_table_short
  [23]:DASHBOARD_trials_count1
  [24]:DASHBOARD_trials_var1
  [25]:DASHBOARD_orcid_table_short
  [26]:DASHBOARD_orcid_count1
  [27]:DASHBOARD_orcid_var1

  "
   
# Plot to graph to the screen / HTML
DiagrammeR::grViz(graph_biomedical_main)

# Export the graph as a PNG image file
F_export_grViz_graph2image(graph_biomedical_main)
#library(DiagrammeRsvg) #https://cran.r-project.org/web/packages/DiagrammeRsvg/index.html
#grViz(graph_biomedical_main) %>%
#    export_svg %>% charToRaw %>% rsvg_pdf("graph_biomedical_main")

# --------------------------------------
### HOW TO RANK rank=same {DATA_PROCESSED_dois, DATA_AcademicObservatory}
### HOW TO LABEL LINES DATA_AcademicObservatory -> P1_Combined_AO_and_Contributed[label = ' @@2 DOIs']
### HOW TO HAVE FOLDERS: data2 [label = 'Dataset 2', shape = folder, fillcolor = Beige]
### HOW TO Include a quote in a label, e.g.   \\' 
### HOW TO:   A cluster is a subgraph placed in its own distinct rectangle of the layout. A subgraph is recognized as a cluster ### when its name has the prefix cluster
### subgraph cluster_A {
### AAAA [label = 'Testing AAA']
### BBBB
#   https://graphviz.org/doc/info/shapes.html

```
